// Hi. I'm randy. It's my job to produce random stuff for you.

function randy(x, y){
    if ( Number.isFinite(x) ){
        return Math.floor( Math.random()*x );
    } else
    // If you give me an array, I'll pick one for you.
    if (Array.isArray(x)){
        return x[ randy(x.length) ];
    } else
    if (x == "name"){
        // Meet the residents
        var first = [
            "Fred",
            "Billy",
            "Sally",
            "Joey",
            "Annis",
            "Willia",
            "Enis",
            "Band",
            "Sam",
            "Old Man",
            "Young Man",
            "Youngins",
            "SAAAAM",
            "Bip",
            "Bop",
            "Jane",
            "Minney",
            "Manney",
            "Mono",
            "Mercury",
            "Will",
            "Phil",
            "Philo",
            "Menos",
            "Rankin",
            "Kalvin",
            "Kale",
            "McJack",
            "Qi",
            "Ji",
            "Lohan",
            "Hazel",
            "Girly",
            "Bear",
            "Alfred",
            "Arnold",
            "Randy",
            "Fern",
            "Jill",
            "Sarah",
            "Sara",
            "Anna",
            "Hanna",
            "Wim",
            "Winnie",
            "Wanton",
            "Wallabie",
            "Winkle",
            "Tinkle",
            "Tim",
            "Bo",
            "Star",
            "Moon",
            "Hanoi",
            "Rufus",
            "Snoopie",
            "Kimmy",
            "Kimberlie",
            "Estonia",
            "Monica",
            "Dhalia",
            "Ananda",
            "Willow", 
            "Deer", 
            "Angora", 
            "Bilderberger", 
            "Rothschild",
            "Anaconda",
            "Someone Else's Friend",
            "Not From Around Here",
            "Senator",
            "Congressman",
            "Donald",
            "Meyers",
            "Derek",
            "Fuckhead",
            "Asshole",
            "Merfolk",
            "Antonio",
            "Derek",
            "Winged",
            "Obi",
            "Wigfred",
            "Maru", 
            "Dash",
            "Mayor",
            "Representative"
        ];
        var middle = [
            "","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",
            '"The Salty" ',
            "Undefined ",
            "Light ",
            "Dark ",
            "Carry ",
            '"Unafraid" ',
            "Random ",
            "Uninvited ",
            "Rodeo ",
            "Look At My",
            "- ",
            "Dash ",
            "Illin ",
            "Not Very Smart ",
            "Brilliant ",
            "Einstein ",
            "Presley ",
            "Parrrsley ",
            "Jack ",
            "McJackie ",
            "Antipasto ",
            "Fetuccini ",
            "Mongolia ",
            "Sudan ",
            "Thai ",
            "Patricia ",
            "Detonation ",
            "Chan ",
            "Never",
            "The Dumbass ",
            "Moron-head ",
            "Eye ",
            "Eyesight ",
            "Hindsight ",
            "EyeGore ",
            "The Pirate ",
            "Menos ",
            "Bobo ",
            "Wanda ",
            "Jam ",
            "Peanut ",
            "Mas ",
            "Max ",
            "The Illuminati ",
            "Mc ",
            "Eli ",
            "Antonio ",
            "Luigi ",
            "Juan ",
            "Anchovie ",
            "Rivaldi ",
            "Regardie ",
            "Crowley ",
            "Wan ",
            "PhD ",
            "Prof. ",
            "Mc",
            "De",
            "Anti-",
            "The",
            "Andy ",
            "Super",
            "Bat-",
            "A",
            "Hip ",,
            "Kittycat ",
            "Bobcat ",
            "III ",
            "IV ",
            "IX ",
            "Regarded ",
            "II ",
            "The Janitor ",
            "Daddy ",
            "Momma ",
            "von",
            "Van",
            "Wilbur ",
            "Taco ",
            '"Can\'t Keep Thier Big Mouth Shut" ' ,
            "Rhetorical ",
            "Dementia-Ridden ",
            "Biden ",
            "Senile ",
            "Terroristic ",
            "Hoff", 
            "Hoss", 
            "Unripe ",
            "Olive Juice ",
            "Not A Robot ",
            "Android ",
            "Extraterrestrial ",
            "Overripe ",
            "Riperian ",
            "Ripper ",
            "Raker ",
            "Hairgel ",
            "Catastrophic ",
            "Stoney ",
            "Avocado ",
            "Battery ",
            "The Lawyer ",
            "Not A Number ",
            "Undefined ",
            "Error-Prone ",
            "Seriously ",
            "$%#& ",
            "Arrivederchi ",
            "Accident-Prone ",
            "The ",
            "Ex Con ",
            "Schoolteacher ",
            "Blue ",
            "Seven ",
            "Sixteen ",
            "Not Sure ",
            "Mac",
            "Mc","Mc","Mc", "Mc",
            "Mc",
            "Gorilla",
            "Snout ",
            "Milkweed ",
            "Nettlestem ",
            "Rhubarb ",
            "Anderson ",
            "Waldo ",
            "Waldorf ",
            "Hitler ",
            "Trudeau ",
            "Trump ",
            "Python ",
            "Frederic "
            
        ];
        var last = [ "","","","","","","","","",
            "Samuelson",
            "Strawberry ",
            "Jammin",
            "Anton",
            "Gremlin",
            "The Last Boss",
            "Not That Important",
            "Amadala",
            "Of Ire",
            "Witgenstein",
            "The Deceiver",
            "Jack",
            "Gore",
            "Bush",
            "Chenie",
            "Gates",
            "Scoundrel",
            "The Vagabond",
            "The Unlucky",
            "The Lucky",
            "The Terrible",
            "The Beloved",
            "Wilburia",
            "The King",
            "The Sasquatch",
            "Faced",
            "Wallbanger",
            "At Your Service",
            "Heated",
            "Undesireable",
            "Victimizer",
            "Understanding",
            "From Far Off Lands",
            "Also Drenched In Sweat",
            "Steve",
            "The Evil Philanthropist",
            "McSenatorr",
            "Anthony",
            "The Jackass",
            "Chi",
            "Pantheon",
            "Cowers",
            "Nighttime",
            "Intosh",
            "Mills And Sons",
            "Lie Gold",
            "The Kid",
            "Crusoe",
            "Kid",
            "Emmerson",
            "Jin",
            "The Poopie",
            "Undersplat",
            "Bilbo",
            "Balboa",
            "Billybongo",
            "Arnolds",
            "Complicated",
            "Of All Time",
            "Jinn",
            "Gin",
            "Gini",
            "Gean",
            "Wanton",
            "Yam",
            "CucumberPatch",
            "Picked",
            "Shirtlogger",
            "Anklegrinder",
            "Max",
            "Vader",
            "Kenobi",
            "Jin",
            "Paraphenalia",
            "Mac",
            "Of The North",
            "Of The South",
            "Of The East",
            "Of The West",
            "Killgore",
            "Idea",
            "Weenis",
            "The Weenis"
        ];
        return (y || first[ randy(first.length) ] )+ " " + // Hi, this is randy. Is randy there?
               middle[ randy(middle.length) ] +
               last[ randy(last.length) ]
    }

}


